version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: lumen_api
    restart: always
    expose:
      - "80"
    environment:
    - APP_NAME=Nolv
    - APP_ENV=production
    - APP_KEY=c0621b4daa11b7eb09353e88dd079d21
    - APP_DEBUG=false
    - APP_URL=http://example.com
    - APP_TIMEZONE=America/Recife
    - MERCHANT_ID=your_merchant_id
    - MERCHANT_SECRET=your_merchant_secret
    - PAGHIPER_KEY=your_paghiper_key
    - PAGHIPER_TOKEN=your_paghiper_token
    - LOG_CHANNEL=stack
    - LOG_SLACK_WEBHOOK_URL=
    - DB_CONNECTION=mysql
    - DB_HOST=db
    - DB_PORT=3306
    - DB_DATABASE=app_db
    - DB_USERNAME=root
    - DB_PASSWORD=secret
    - CACHE_DRIVER=file
    - QUEUE_CONNECTION=sync
    - MAIL_MAILER=smtp
    - MAIL_HOST=smtp.mailtrap.io
    - MAIL_PORT=2525
    - MAIL_USERNAME=your_mail_username
    - MAIL_PASSWORD=your_mail_password
    - MAIL_ENCRYPTION=tls
    - MAIL_FROM_ADDRESS=hello@example.com
    - MAIL_FROM_NAME="Example app"
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: quasar_front
    restart: always
    expose:
      - "80"
    depends_on:
      - api
    environment:
      - VUE_APP_API_URL=http://localhost/api/

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - front

volumes:
  db_data:
