version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: lumen_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=app_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: quasar_front
    restart: always
    ports:
      - "8080:8080"
    environment:
      - LUMEN_API=http://dynamic-api-url.com
    command: ["quasar", "build"]

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
